api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("exams-event/", views.examList, name="exam-list"),
    path("exams-summary/<str:pk>/", views.examSummary, name="exams-summary"),
    
    
    path("assessment-data/", views.studentResultData, name="assessment-data"),
    path("save-assessment-data/", views.save_assessment_data, name="save_assessment_data"),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import settings
from django.conf.urls.static import static

# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    # path("admin/password_reset/",auth_views.PasswordResetView.as_view(),name="admin_password_reset",),
    # path("admin/password_reset/done/",auth_views.PasswordResetDoneView.as_view(),name="password_reset_done",),
    # path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm",),
    # path("reset/done/",auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete",),
    
    path("", include("users.urls")),
    path("teacher/", include("teachers.urls")),
    path("student/", include("students.urls")),
    path("admins/", include("custom_admin.urls")),
    path("api/", include("api.urls")),
    path("tinymce/", include('tinymce.urls'),),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header  =  "Skodaji Admin"  
admin.site.site_title  =  "Skodaji manager site"
admin.site.index_title  =  "Skodaji Admin home"

handler404 = 'users.views.pageNotFound'

teachers/urls.py
from django. urls import path
from . import views

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/", views.userProfile, name="profile"),
    path("edit-profile/<str:pk>/", views.editProfile, name="edit-profile"),
    path("image/<str:pk>/", views.editProfileImage, name="edit-profile-image"),
    path("exam/", views.scheduledExam, name="scheduled-exam"),
    path("closed-exam/", views.closedExam, name="closed-exam"),
    path("exam/<str:pk>/edit/", views.editExam, name="edit-exam"),
    path("exam/delete/", views.deleteExam, name="delete-exam"),
    # path("exam/<str:pk>/", views.viewExam, name="view-exam"),
    # path("exam/<str:pk>/question/edit/", views.editQuestion, name="view-question"),
    path("exam/<str:pk>/question/delete/", views.deleteQuestion, name="delete-question"),
    path("session-dashboard/<str:pk>/", views.sessionDashboard, name="session-dashboard"),
    path("analysis/<str:pk>/", views.studentPerformance, name="student-performance"),
    path("exam-dashboard/<str:pk>/", views.examDashboard, name="exam-dashboard"),
    path("new-exam-dashboard/<str:pk>/", views.newExamDashboard, name="new-exam-dashboard"),
    
    
    path("all-topics/", views.allTopics, name="all-topics"),
    path("add-topic/", views.addTopic, name="add-topic"),
    path("topic-data/", views.topicsData, name="topic-data"),
    path("edit-topic/", views.editTopic, name="edit-topic"),
    path("delete-topic/", views.deleteTopic, name="delete-topic"),
    
    
    path("questions", views.allQuestions, name="all-questions"),
    path("question-data", views.questionData, name="question-data"),
    
    # path("create-question", views.createQuestion, name="create-question"),
    # path("delete-question", views.deleteQuestion, name="delete-question"),
    # path("edit-question", views.editQuestion, name="edit-question"),
    
    
    #debugging-------------------------------------------
    path("create-myquestion", views.question_create, name="create-myquestion"),
    path("edit-myquestion/<str:pk>/", views.question_edit, name="edit-myquestion"),
    path("delete-myquestion/", views.question_delete, name="delete-myquestion"),
    path("update-topic/", views.update_topics, name="update-topic"),
    path("convert-to-docx/", views.convertToDocx, name="docx"),
    path("template-to-docx/", views.prepareDocxTemplateForExam, name="template-docx"),
    path("uploaded-docx/", views.handleUploadedDocx, name="upload-docx"),
    #debugging-------------------------------------------
    
    
    path("session-data/<str:pk>/", views.sessionDashboardData, name="session-data"),
    path("exam-data/<str:pk>/", views.examDashboardData, name="exam-data"),
   
    
    
    path("exam/<str:pk>/", views.viewExam, name="view-exam"),
    path("assign-question-to-exam/<str:pk>/", views.assignQuestionToExam, name="assign-question-to-exam"),
    path("remove-question-from-exam/<str:pk>/", views.removeQuestionFromExam, name="remove-question-from-exam"),
    
    
    path("AI-explanation", views.explanationWithAI, name="AI-explanation"),
    path("update-explanation", views.SavegenerateExplanation, name="update-explanation"),
    path("change-students-password", views.changeStudentsPassword, name="change-students-password"),
    path("AI-exam-explanation", views.generateExamSummary, name="AI-exam-explanation"),

    path("assessment/<str:pk>/", views.assessment, name="assessment")
]

exam/models.py
from collections import defaultdict
from urllib import request
from django.db import models
from requests import session
from users. models import User
from school.models import Grade, Subject, AcademicYear, Term
from teachers. models import Topic
from django.utils import timezone
from django.db.models import UniqueConstraint,Q

from django.contrib import admin


from datetime import date
# from django_ckeditor_5.fields import CKEditor5Field
  

STATUS = [
    ("active", "ACTIVE"), 
    ("pending", "PENDING")
]
    
# Create your models here.
class Exam(models.Model):
    name = models.CharField(max_length=100, unique=True)
    grade = models.ForeignKey(Grade, on_delete=models.SET_NULL, null=True)
    teacher = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, limit_choices_to={"is_teacher":True})
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
    duration = models.DurationField()
    pass_mark = models.FloatField(verbose_name="Pass mark", default=60)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    ready = models.BooleanField(default=False) #to make sure exam satisfy every requirements like no. of quest etc before students can see it
    deleted = models.BooleanField(default=False)
    review = models.BooleanField(default=False)
    retake = models.BooleanField( default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    
    
    def __str__(self):
        return self.name
    
    
    
    @property
    def get_exam_status(self):
        now = timezone.localtime(timezone.now())
        startExam = timezone.localtime(self.start_date)
        endExam = timezone.localtime(self.end_date)

        if now < startExam:
            return "pending"
            
        if now> startExam  and now< endExam:
            return "active"
            
        if now> startExam and now> endExam:
            return "ended"

       
                      
                                                    
    @property
    def get_no_question(self):
        return self.question_set.all().count()
    
    @property
    def get_all_question(self):
        return self.question_set.all()
    
    @property
    def seconds_to_hms(self):
        duration = self.duration.seconds
        hours = int(duration // 3600)
        minutes = int((duration % 3600) // 60)
        seconds = int(duration % 60)
        
        return f"{str(hours) + 'hr' if hours > 0 else ''}{'s' if hours>1 else ''} {str(minutes) + 'min ' if minutes > 0 else ''} {str(seconds) + 'sec(s)' if seconds > 0 else ''}".strip()
    
    def duration_to_minutes(self):
        duration = self.duration.seconds
        minutes = int(duration / 60)
        return minutes
        
        
        
    def topic_count(self):
        """
        Calculate the count of unique topics for the questions associated with the current exam instance.

        This method retrieves all questions related to the current exam instance and creates a dictionary
        with the names of the topics as keys and 0 as the value, indicating the initial count. It also
        compiles a list of question IDs that do not have an associated topic.

        Returns:
            dict: A dictionary with topic names as keys and 0 as the value for each key.
        """
        questions = self.question_set.all()
        topics_count = defaultdict(dict)
        questions_without_topic = list()
        for question in questions.select_related("topics"):
            if question.topics:
                topic_name = question.topics.name  # Assuming the Topic model has a 'name' field
                topics_count[topic_name] = {"correct": 0, "incorrect":0, "unanswered": 0, "no_questions":0}
            else:
                questions_without_topic.append(question.id)
        return dict(topics_count), questions_without_topic
    
    def delete(self, *args, **kwargs):
        # super(Exam).delete(*args, *kwargs)
        
        if self.get_exam_status in ["ended"]:
            sessions = self.session_set.exists()
            
            if (sessions):
                self.name = f"{self.name} (Archived {timezone.now().strftime('%Y-%m-%d %H:%M:%S')})"
                self.deleted = True
                self.save()
            else:
                super().delete(*args, **kwargs)
        else:
            super().delete(*args, **kwargs)              
        
    class Meta:
        ordering = [ "created"]           
        
    
    
class Question(models.Model):
    # teacher = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, limit_choices_to={"is_teacher":True})
    subject = models.ForeignKey(Subject, on_delete=models.RESTRICT, blank=False)
    # exam = models.ForeignKey(Exam, on_delete=models.SET_NULL, null=True, blank=True)
    exam = models.ManyToManyField(Exam,)
    topics = models.ForeignKey(Topic, on_delete=models.SET_NULL, blank=True, null=True)
    question = models.TextField(unique=True)
    option_A = models.TextField()
    option_B = models.TextField()
    option_C = models.TextField()
    option_D = models.TextField()
    answer =  models.CharField(max_length=250)
    explanation = models.CharField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.question
    
    class Meta:
        ...
        # ordering = [ "-created"]
    
    
class Session(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE,)
    # exam = models.ForeignKey(Exam, on_delete=models.SET_NULL, null=True)
    score = models.FloatField(default=0.0)
    elapsed_time = models.FloatField(null=True)
    attempts = models.IntegerField(default=0)
    misconduct = models.BooleanField(default=False)
    time_started = models.DateTimeField(null=True)
    time_ended = models.DateTimeField(auto_now=True)
    completed = models.BooleanField(default=False)
    choices = models.JSONField(default=dict)
    
    
    def __str__(self):
        return str(self.pk)
    
    @property
    def passed(self):
        if self.score >= self.exam.pass_mark:
            return "Passed"
        else:
            return "Fail"
        
    def seconds_to_hms(self):
      
        if self.elapsed_time > 0:
            hours = int(self.elapsed_time // 3600)
            minutes = int((self.elapsed_time % 3600) // 60)
            seconds = int(self.elapsed_time % 60)
            
            
            return f"{str(hours) + 'h ' if hours > 0 else ''} {str(minutes) + 'm ' if minutes > 0 else ''} {str(seconds) + 's' if seconds > 0 else ''}"
        else:
            return "-"
    
    def get_correct_count(self):
        choices_data = self.choices
        correct = 0
        incorrect = 0
        unanswered = 0
        
        for option in choices_data.values():
            if option[1].get("status") == "correct":
                correct += 1
            elif option[1].get("status") == "incorrect":
                incorrect += 1
            elif option[1].get("status")== "unanswered":
                unanswered += 1
                    
        return correct, incorrect, unanswered


# class StudentAnswer(models.Model):
#     session = models.ForeignKey(Session, on_delete=models.CASCADE)
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice = models.CharField(max_length=255)
#     status = models.CharField(max_length=10)  # e.g., "correct", "incorrect", "unanswered"


class StudentResult(models.Model):
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE)
    term = models.ForeignKey(Term, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)

    # Continuous Assessment Fields
    first_cat = models.FloatField(blank=True, null=True)  # The '1st CAT' column
    second_cat = models.FloatField(blank=True, null=True)  # The '2nd CAT' column

    # Test Fields
    first_test = models.FloatField(blank=True, null=True)  # The '1st Test' column
    second_test = models.FloatField(blank=True, null=True)  # The '2nd Test' column

    # Exam Field
    exam_score = models.FloatField(blank=True, null=True)  # The 'Exam' column

    # Computed Fields (can be calculated in your views or forms)
    total_score = models.FloatField(blank=True, null=True)  # The 'Total' column
    remark = models.CharField(max_length=255, blank=True, null=True)  # The 'Remark' column
    position = models.PositiveIntegerField(blank=True, null=True)  # The 'Position' column

    def __str__(self):
        return "Yes"   

    def save(self, *args, **kwargs):
        self.total_score = sum(filter(None, [
            self.first_cat, self.second_cat,
            self.first_test, self.second_test,
            self.exam_score
        ]))
        super().save(*args, **kwargs)

teachers/models.py
from tabnanny import verbose
from django.db import models

from school.models import Grade, Level, Subject


        
class Topic(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    grade = models.ForeignKey(Grade, on_delete= models.CASCADE, null=True)
    name = models.CharField(max_length=225)
    
    class META:
        ordering = ("subject__name","name")
        
    def __str__(self) :
        return self.name
    
    

teachers/templates/teachers/all_questions.html
{% extends "main.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}All questions{% endblock title %}

{% block additional_head_css %}
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.22.2/dist/bootstrap-table.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

{% comment %} <style>
  

  table, th, td {
      border: 1px solid black; /* Defines a 1px solid black border for table, th, and td */
      padding: 8px; /* Adds some padding to table cells */
  }

  
</style> {% endcomment %}

{% endblock additional_head_css %}
{% block content %}

<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:void(0)">Teacher</a></li>
        <li class="breadcrumb-item active" aria-current="page">All Questions</li>
    </ol>
</nav>
<div id="alert">
  {% comment %} notification {% endcomment %}
</div>
<div class="d-grid mt-3 gap-2 d-block">
    <button type="button" class="btn btn-primary js-create-question" >
        <i class="fas fa-plus fa-lg"></i> Add Question
    </button>
</div>


<div id="toolbar" class="input-group ">
	<button id="remove" class="btn btn-danger" disabled ><i class="fa fa-trash"></i> Delete</button>
	<button id="docx" class="btn btn-secondary" type="button" disabled><i class="fa fa-file-word"></i> Convert to Docx</button>
 
	
 
</div>
<!-- data-toggle="table" Activates bootstrap table without writing JavaScript.-->
<table
    id="table" {% comment %} instanciate the table  {% endcomment %}
    data-toggle="table"
    data-ajax = "ajaxRequest" {% comment "" %}request{% endcomment %}
    data-side-pagination="server" {% comment "" %}"server" or "client"{% endcomment %}
    data-pagination="true"
    data-pagination-pre-text="<"
    data-pagination-next-text=">"
    data-search="true"
    data-page-list = "[5, 25, 50, 100, 200, 400]"
    data-pagination-loop = "false"
    data-page-size = "25"   {% comment "" %}default no of rows{% endcomment %}
    data-cache= "false"

    data-search-highlight ="true"
    data-toolbar="#toolbar"
    data-click-to-select="false" {% comment "" %}click a row to select{% endcomment %}
    data-unique-id="id" {% comment "" %}Indicate a unique identifier for each row.{% endcomment %}
    data-detail-view="true" {% comment "" %}to show a detailed view table{% endcomment %}
	  data-detail-view-by-click="false"
    data-detail-formatter="detailFormatter" {% comment "" %}to show detail view table.{% endcomment %}
    
>
  <thead>
    <tr>
      <th data-field="check" data-checkbox="true"></th>
      <th data-field="#" data-formatter="numberingFormatter">#</th>
      <th data-field="question" data-cell-style="questionCellStyle">Question</th>
      <th data-field="exam__name" data-cell-style="examCellStyle">Exam</th>
      <th data-field="answer">Answer</th>
      <th data-field="subject__name" >Subject</th>
      <th data-field="operate" data-formatter="operateFormatter"   data-events="operateEvents" data-align="center"></th> 
    </tr>
  </thead>

</table>


{% comment %} <div class="modal" id="addQuestion">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add question</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            
        </div>
      </div>
    </div>
</div> {% endcomment %}

{% comment %} <form method="POST" id="question-data" action="{% url "create-myquestion" %}" class="js-question-create-form" novalidate> {% endcomment %}
<form method="POST" id="question-data" class="js-question-create-form">
  {% csrf_token %}
	<div class="modal fade" id="addQuestion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
		<div class="modal-dialog modal-fullscreen">
			<div class="modal-content">

       
        
				<div class="modal-header ">
					<h4 class="modal-title text-center">Add Question</h4>
					<button type="reset" class="btn-close" data-bs-dismiss="modal" onclick="clearForm()"></button>
				</div>
				<div class="modal-body">
					{{form | crispy}}
          
				</div>
				<!-- Modal footer -->
				<div class="modal-footer d-flex justify-content-between">
					<button type="submit" class="btn btn-success"  value="false">Save</button>
					<button type="submit" class="btn btn-success"  value="true">Save and add another</button>
				</div>

        
			</div>
		</div>
	</div>
</form>

{% include "modal.html" with message="Are you sure you want to delete these question(s)?" %}
{% endblock content %}


{% block js %}
{{form.media}}
<script src="https://unpkg.com/bootstrap-table@1.22.2/dist/bootstrap-table.min.js"></script>





<script src="{% static "js/questions.js" %}?tree=1eet9" defer></script>




{% endblock js %}

teachers/templates/teachers/edit.html
{% extends "main.html" %}
{% load crispy_forms_tags %}

{% block additional_head_css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

{% endblock additional_head_css %}

{% block content %}
    <!--<div class="card mb-4 mt-3 p-5">
    </div>-->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Teacher</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Exam</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit Exam</li>
        </ol>
    </nav>
    <div class="card mx-auto w-100 ">
        <div class="card-body text-justify">
          <h3 class="card-title text-danger">EDIT {{obj_name}}</h3>
          
          
          <form action="" method="post">
          
                {% csrf_token %}
                {% crispy form %}
                
            
        </form>
        </div>
      </div>
{% endblock content %}

{% block js %}

      <script>
        function convertMinutesToHoursAndMinutes(minutes) {
            let hours = Math.floor(minutes / 60);
            let remainingMinutes = minutes % 60;
            return `${hours>1 ? `${hours} hours`: `${hours} hour`} ${remainingMinutes>0 ? `and ${remainingMinutes}minutes` : ""}`;
        }

        $("#id_retake").on("change", function(){
            if ($("#id_retake").is(":checked")){
                // if retake is on, check that the review too is on
                if (!$("#id_review").prop("checked")){
                    $("#id_review").prop("checked", true)
                    $("#hint_id_retake span").text("Students must see score first before they can retake this exam")
                }
            }else{
                $("#hint_id_retake span").text("")
            }
        })
    
        $("#id_review").on("change", function(){
            //prevent teacher from toggling off the review button when retake is on
            if ($("#id_retake").is(":checked")){
                $("#id_review").prop("checked", true)
                $("#hint_id_retake span").text("Exam retake option in on")
            }
        })

        $("#id_duration").on("input", function(){
            $(this).val() + ` MINS ~ ${convertMinutesToHoursAndMinutes($(this).val())}`
            $("#hint_id_duration span").text(`${$(this).val() >= 60 ? convertMinutesToHoursAndMinutes($(this).val()): $(this).val()+ " Mins" }`)
        })


        document.addEventListener('DOMContentLoaded', function() {
            flatpickr(".flatpickr-date", {
                wrap: true,
                altInput: true,
                
            });
        });
      </script>
{% endblock js %}

teachers/templates/teachers/topics.html
{% extends "main.html" %}
{% load crispy_forms_tags %}

{% block additional_head_css %}
<style>


    .action_btn{
        display: none;
    }

    li:hover{
        background-color: #f2f2f2;
    }

    li:hover > div .action_btn {
        display:inline-block;
    }
</style>
{% endblock additional_head_css %}

{% block content %}
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:void(0)">Teacher</a></li>
        <li class="breadcrumb-item active" aria-current="page">Topics</li>
    </ol>
</nav>

<div id="alert">
    {% comment %} notification {% endcomment %}
</div>

<div class="row">
    <div class="col-md-4 mb-2">
        <form id="edit-topic-form" class="d-none">
            <h2>Edit topic</h2>
            {% csrf_token %}
            <input type="hidden" name="id">
            {{form | crispy}}

            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-success">Save</button>
            </div>
        </form>

        <form id="topic-form" >
            <h2>Add topics</h2>
            {% csrf_token %}
            <!--form for adding Topics-->
            {{form | crispy}}
            
            {% comment %} {{form.subject| as_crispy_field}}

            <div class="mb-5"> <label for="id_name" class="form-label requiredField">
                Topic name<span class="asteriskField">*</span> 
            </label> 


            <input type="text" name="name" maxlength="225" class="textinput form-control" required="" id="id_name"> 
            </div> {% endcomment %}

            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-success once">Save</button>
                <button type="submit" class="btn btn-success">Save and add another</button>
            </div>
        </form>
    </div>
    <div class="col-md-8" >
        <select name="grade" id="class_filter" class="form-select">
            {% for grade in grades  %}
                <option value="{{grade.id}}">{{grade}}</option>
            {% endfor %}
        </select>
        <div id="topic_area"></div>
        {% comment %} {% for subject in subjects %}
            <h2 class="text-center">{{subject.name}}</h2>
            <ul>
                {% for topic in subject.topic_set.all %}
                    <li>{{topic.name}}</li>
                {% endfor %}
            </ul>
        {% endfor %} {% endcomment %}
        
    </div>
</div>
{% endblock content %}


{% block js %}
    <script>

        //adding topics
       $(document).ready(function(){
        let form = $("#topic-form")
        form.submit(function(event){
            event.preventDefault()
            data = form.serialize()
            $.ajax({
                type: "POST",
                url: window.origin + "/teacher/add-topic/",
                data: data,
                success: function (success){
                    if (success){
                        createToast('success', success.message);
                    }else{
                        createToast('danger', "Oops... Something went wrong");
                    }
                    
                        //reset form after adding a question
                    if ($('button[type="submit"]:focus').hasClass('once')){
                        $("#topic-form")[0].reset()
                    }else{
                        $("#topic-form input[name=name]").val("")
                    }
                    getTopicData()
                },
                error: function(error){
                    createToast('danger', "Oops... Something went wrong");
                }
            })
        })
       })

         //editing topics
         $(document).ready(function(){
            let form = $("#edit-topic-form")
            form.submit(function(event){
                event.preventDefault()
                data = form.serialize()
                $("#edit-topic-form").hide()
                $("#topic-form").show()
                $.ajax({
                    type: "POST",
                    url:  window.origin + `/teacher/edit-topic/`,
                    data: data,
                    success: function (success){
                        if (success){
                            createToast('success', success.message);
                        }else{
                            createToast('success', success.message);
                        }
                        getTopicData()
                    },
                })

                
            })
           })
let obs
const getTopicData = (url=window.origin + "/teacher/topic-data/" +`?grade=${$("#class_filter").val()}`)=>{
    $.ajax({
        type: "GET",
        url: url,
        success: function (success){
            obs = success
            
            let topic = ""
            // Loop through each subject
            for (const subject in obs) {
                
                topic += `<h2 class=" mt-2 text-center bg-dark text-light">${subject}</h2>`
            
                
                    if (obs[subject].length>0){
                        // Loop through each topic in the subject
                        topic += "<ol class='list-group list-group-numbered'>"
                        for (const sub_topic of obs[subject]) {
                            topic += `<li class='list-group-item position-relative'>
                                <span>${sub_topic.name}</span> 
        
                                
                                <div class="position-absolute top-0 end-0 mt-1">
                                    <button onclick="scroller(); actionBtn(this);" class="action_btn btn btn-sm btn-light" data-action="edit" data-id=${sub_topic.id} data-subject=${subject}><i class="fas fa-pencil"></i></button>
                                    <button onclick="actionBtn(this)" class="action_btn btn btn-sm btn-light text-danger me-2" data-action="delete" data-id=${sub_topic.id}><i class="fas fa-trash"></i></button>
                                </div>
                            
                            </li>`
                            
                        }
                        topic += "</ol>"
                    }else{
                        topic += `<p class='text-center fs-3'>No topic at the moment</p> `
                    }
                
            }
            $("#topic_area").html(`${topic}`)
           
            
        },
    })
    
}
getTopicData()


//when a select option changes
$("#class_filter").on("change", function(){
    //getTopicData(url=window.origin + "/teacher/topic-data/"+`?grade=${$(this).val()}`)
    getTopicData()
})

function scroller(){
    var element = document.getElementById("edit-topic-form")
    element.scrollIntoView({behavior: "smooth", block: "end", inline: "nearest"})   
}




//action btn click
function actionBtn(n){
    let action= n.getAttribute("data-action")
    if (action === "edit"){
        $("#topic-form").hide() // hideing creation form
        let id= n.getAttribute("data-id")
        let subject = n.getAttribute("data-subject")
        let topic_data = obs[subject].find(topic => topic.id == id) //output: {id: 20, subject: 1, name: 'Another one big God'}

        $("#edit-topic-form input[name=id]").val(topic_data.id)
        $("#edit-topic-form input[name=name]").val(topic_data.name)
        $("#edit-topic-form select[name=subject]").val(topic_data.subject)
        
        if (topic_data.grade){
            $("#edit-topic-form select[name=grade]").val(topic_data.grade)
        }


        $("#edit-topic-form").removeAttr("class").show() //displaying edit form
        //console.log($("#edit-topic-form select[name=subject]"))
    }
 
    if (action === "delete"){
        let id= n.getAttribute("data-id")
        $.ajax({
            type: "POST",
            url: window.origin + "/teacher/delete-topic/",
            data: {"csrfmiddlewaretoken": "{{csrf_token}}", "id": id},
            success: function(success){
                createToast('success', success.message);
                getTopicData()
            },
            error: function(error){
                createToast('danger', "Oops... Something went wrong");
            }
        })
    }
 
 }



    </script>
{% endblock js %}