api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("exams-event/", views.examList, name="exam-list"),
    path("exams-summary/<str:pk>/", views.examSummary, name="exams-summary"),
    
    
    path("assessment-data/", views.studentResultData, name="assessment-data"),
    path("save-assessment-data/", views.save_assessment_data, name="save_assessment_data"),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import settings
from django.conf.urls.static import static

# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("django.contrib.auth.urls")),
    # path("admin/password_reset/",auth_views.PasswordResetView.as_view(),name="admin_password_reset",),
    # path("admin/password_reset/done/",auth_views.PasswordResetDoneView.as_view(),name="password_reset_done",),
    # path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm",),
    # path("reset/done/",auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete",),
    
    path("", include("users.urls")),
    path("teacher/", include("teachers.urls")),
    path("student/", include("students.urls")),
    path("admins/", include("custom_admin.urls")),
    path("api/", include("api.urls")),
    path("tinymce/", include('tinymce.urls'),),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header  =  "Skodaji Admin"  
admin.site.site_title  =  "Skodaji manager site"
admin.site.index_title  =  "Skodaji Admin home"

handler404 = 'users.views.pageNotFound'

school/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=255, unique=True)
    motto = models.CharField(max_length=255, null=True)
    address = models.TextField()
    contact_numbers = models.CharField(max_length=50)  # Store multiple numbers as comma-separated values
    logo = models.ImageField(upload_to='school_logos/', blank=True, null=True)  
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Level(models.Model):
    """Levels just like senoir secondary or Junior Secondary"""
    name = models.CharField(max_length=50)
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='levels', null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

class Grade(models.Model):
    name= models.CharField(max_length=50, null=True)
    grade = models.IntegerField()
    level = models.ForeignKey(Level, on_delete=models.SET_NULL, null=True)
    
    
    class Meta:
        ordering = ["grade"]
    
    def __str__(self):
        return self.name
        # return f"Grade {str(self.grade)}"
    

class Subject(models.Model):
    name = models.CharField(max_length=25, unique=True)
    teacher = models.ForeignKey("users.User", on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={"is_teacher":True})
    assigned = models.BooleanField(default=False)
    grade = models.ManyToManyField(Grade, related_name="subject")
    
    def __str__(self):
        return self.name 
    
    def clean_name(self):
        self.name = self.name.capitalize()
    
    def save(self, *args, **kwargs):
        self.clean_name
        if self.teacher is not None:
            self.assigned = True
        else:
            self.assigned= False
        super(Subject, self).save(*args, **kwargs)
       
    class Meta:
        ordering = ["name"]





class AcademicYear(models.Model):
    """Represents a school session (e.g., 2023/2024)."""
    name = models.CharField(max_length=20, unique=True)  # e.g., "2023/2024"
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='academic_years')
    is_current = models.BooleanField(default=False)  # Tracks if this is the current session

    def __str__(self):
        return f"{self.name} session"

    def save(self, *args, **kwargs):
        if self.is_current:
            # Ensure only one active session per school
            AcademicYear.objects.filter(school=self.school, is_current=True).update(is_current=False)
        
        super().save(*args, **kwargs)

    def clean(self):
        if self.is_current:
            # Check if another current session exists for the same school
            if AcademicYear.objects.filter(school=self.school, is_current=True).exclude(pk=self.pk).exists():
                raise ValidationError("There can only be one active academic session for your school.")
        super().clean()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['school'], condition=models.Q(is_current=True), name='unique_current_academic_year_per_school')
        ]
    
class Term(models.Model):
    """Represents a term within a school session."""
    name = models.CharField(max_length=50)
    academic_year = models.ForeignKey(AcademicYear, on_delete=models.CASCADE, related_name='terms')
    # weeks = models.PositiveIntegerField()
    start_date = models.DateField()
    end_date = models.DateField()


    def __str__(self):
        return f"{self.name}"
    

    def clean(self):
        # Check for overlapping dates within the same academic year
        overlapping_terms = Term.objects.filter(
            academic_year=self.academic_year,
            start_date__lt=self.end_date,
            end_date__gt=self.start_date
        ).exclude(pk=self.pk)  # Exclude the current term from the check

        if overlapping_terms.exists():
            raise ValidationError(
                _("The dates for this term overlap with another term in the same academic year.")
            )

        # Ensure start date is before end date
        if self.start_date >= self.end_date:
            raise ValidationError(
                _("The start date must be before the end date.")
            )

        super().clean()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['academic_year', 'name'], name='unique_term_per_academic_year')
        ]

templates/basic.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
  <head>
    
    <script>
      (() => {
        'use strict'

        const getStoredTheme = () => localStorage.getItem('theme')
        const setStoredTheme = theme => localStorage.setItem('theme', theme)

        const getPreferredTheme = () => {
          const storedTheme = getStoredTheme()
          if (storedTheme) {
            return storedTheme
          }

          return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
        }

        const setTheme = theme => {
          if (theme === 'auto') {
            document.documentElement.setAttribute('data-bs-theme', (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'))
          } else {
            document.documentElement.setAttribute('data-bs-theme', theme)
          }
        }

        setTheme(getPreferredTheme())

        const showActiveTheme = (theme, focus = false) => {
          const themeSwitcher = document.querySelector('#bd-theme')

          if (!themeSwitcher) {
            return
          }

          const themeSwitcherText = document.querySelector('#bd-theme-text')
          const activeThemeIcon = document.querySelector('.theme-icon-active use')
          const btnToActive = document.querySelector(`[data-bs-theme-value="${theme}"]`)
          const svgOfActiveBtn = btnToActive.querySelector('svg use').getAttribute('href')

          document.querySelectorAll('[data-bs-theme-value]').forEach(element => {
            element.classList.remove('active')
            element.setAttribute('aria-pressed', 'false')
          })

          btnToActive.classList.add('active')
          btnToActive.setAttribute('aria-pressed', 'true')
          activeThemeIcon.setAttribute('href', svgOfActiveBtn)
          const themeSwitcherLabel = `${themeSwitcherText.textContent} (${btnToActive.dataset.bsThemeValue})`
          themeSwitcher.setAttribute('aria-label', themeSwitcherLabel)

          if (focus) {
            themeSwitcher.focus()
          }
        }

        window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {
          const storedTheme = getStoredTheme()
          if (storedTheme !== 'light' && storedTheme !== 'dark') {
            setTheme(getPreferredTheme())
          }
        })

        window.addEventListener('DOMContentLoaded', () => {
          showActiveTheme(getPreferredTheme())

          document.querySelectorAll('[data-bs-theme-value]')
            .forEach(toggle => {
              toggle.addEventListener('click', () => {
                const theme = toggle.getAttribute('data-bs-theme-value')
                setStoredTheme(theme)
                setTheme(theme)
                showActiveTheme(theme, true)
              })
            })
        })
      })()
    </script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Martins Madueke">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/fontawesome-6-pro@6.4.0/css/all.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      @media (max-width: 768px) {
        body {
            font-size: 12px; /* Adjust font size for phones */
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }



      html,body {
        height: 100%;
      }

      .form-signin {
        max-width: 330px;
        padding: 1rem;
      }


      .form-signin .form-floating:focus-within {
        z-index: 2;
      }

    

      .form-signin input[type="text"], .form-signin input[type="password"], .form-signin input[type="email"] {
        margin-bottom: 10px;
        border-radius: 2px
      }

    </style>

    
    <!-- Custom styles for this template -->
    
  </head>
  <body class="py-4 bg-body-tertiary">
     {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show mt-2 text-center" role="alert">
            {{message}}.
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}
   
    <div class="flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check2" viewBox="0 0 16 16">
          <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
        </symbol>
        <symbol id="circle-half" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
        </symbol>
        <symbol id="moon-stars-fill" viewBox="0 0 16 16">
          <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
          <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
        </symbol>
        <symbol id="sun-fill" viewBox="0 0 16 16">
          <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
        </symbol>
      </svg>
  
      <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
        <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
                id="bd-theme"
                type="button"
                aria-expanded="false"
                data-bs-toggle="dropdown"
                aria-label="Toggle theme (auto)">
          <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
          <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
          <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
              <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
              Light
              <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
          </li>
          <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
              <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
              Dark
              <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
          </li>
          <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
              <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
              Auto
              <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
            </button>
          </li>
        </ul>
      </div>
  
      {% block content %}
  
      {% endblock content %} 
      <p class="mt-5 mb-3 text-body-secondary text-center">&copy; 2017–2024</p>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block js %}{% endblock js %}
  </body>
</html>

templates/login_registration.html
{% extends "basic.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

{% if page == "login" %}

<main class="form-signin w-100 m-auto">
    
    <form method="post">
        <img class="mb-2 mx-auto d-block" src="{% static "images/logo.png" %}" alt="Logo" width="100" height="100">
        {% csrf_token %}
        <h3 class="h3 mb-3 fw-normal">Please sign in</h3>
    
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" placeholder="Username" name="username">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password">
            <label for="floatingPassword">Password</label>
        </div>
    
        <div class="form-check text-start my-3">
            <input class="form-check-input" id="showPassword" type="checkbox"/>
            <label class="form-check-label" for="showPassword">Show Password</label>
        </div>
        <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
            <a class="small" data-bs-toggle="modal" data-bs-target="#status" style="cursor: pointer">Forgot Password?</a>
            <a href="{% url "register" %}"> Sign up!</a>
        </div>
        <button class="btn btn-primary w-100 py-2 mt-2" type="submit" onclick="toggleSubmitBtn()"> Sign in <i class="fas"></i></button>
        
    </form>


    

{% else %}
  <main class="form-signin w-100 m-auto" style="max-width:700px">
    <form action="" method="post" novalidate >
        {% csrf_token %}
        <img class="mb-2 mx-auto d-block" src="{% static "images/logo.png" %}" alt="" width="100" height="100">
        <h3 class="h3 mb-3 fw-normal">Register</h3>
        <!-- {{form | crispy}} -->
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="form-floating mb-3 mb-md-0">
                    {{form.first_name | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-floating mb-3 mb-md-0">
                    {{form.last_name | as_crispy_field}}
                </div>
            </div>
        </div>
        <div class="form-floating mb-3 mb-md-0">
            {{form.username | as_crispy_field}}
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="form-floating mb-3 mb-md-0">
                    {{form.password1 | as_crispy_field}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-floating mb-3 mb-md-0">
                    {{form.password2 | as_crispy_field }}
                </div>
            </div>
        </div>
        <div class="form-floating mb-3 mb-md-0">
            {{form.role | as_crispy_field}}
        </div>
        <div class="d-flex align-items-center justify-content-end mt-4 mb-0">
            <a href="{% url "login" %}"> Sign in!</a>
        </div>
        <button class="btn btn-primary w-100 py-2 mt-2" type="submit">Create account</button>
        
    </form>
  </main>
{% endif %}




<!-- Modal -->
<div class="modal fade opacity-75" id="status"  data-bs-keyboard="true" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-body">
            <a class="d-flex justify-content-between bg-light py-2 px-3 text-decoration-none border border-dark rounded-pill " href="{% url "reset_password_student" %}">
                <span  class="text-decoration-underline fw-bold">Student</span>
                <i class="mt-1 fas fa-arrow-circle-right fa-beat"></i>
            </a>
            <a class=" mt-2 d-flex justify-content-between bg-light py-2 px-3 text-decoration-none border border-dark rounded-pill" href="{% url "reset_password" %}">
                <span class="text-decoration-underline fw-bold">Teacher</span>
                <i class="mt-1 fas fa-arrow-circle-right fa-beat"></i>
            </a>
        
        </div>
        
    </div>
    </div>
</div>
</main>

{% endblock content %}

{% block js %}
<script>
    
    $password = $("input[type=password]")
    $showPassword = $("#showPassword")
    $showPassword.on("change", function(event){
        if ($password.attr("type") == "password"){
            $password.attr("type", "text")
        }else{
            $password.attr("type", "password")
        }

    })
    
    const toggleSubmitBtn = () => {
        let btn= $("button[type=submit] .fas")
        if (btn){
            btn.toggleClass("fa-spinner fa-spin")
        }
        
    }

  
</script>
{% endblock js %}

templates/modal.html
<div class="modal" id="{{type_of_modal |default:"delete"}}">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header ">
          <h4 class="modal-title text-center">Delete</h4>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
  
        <!-- Modal body -->
        <div class="modal-body" id="modal-body-confirm">
            <p>{{message | default:"Are you sure you want to delete?"}}</p>
        </div>
  
        <!-- Modal footer -->
        <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
              <form id="deleteForm">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" id="confirmDelete">Delete</button>
              </form>
          
        </div>
  
      </div>
    </div>
</div>

templates/reset_password.html
{% extends "basic.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<main class="form-signin w-100 m-auto" style="max-width:400px">
    <form method="post">
        {% csrf_token %}
        <img class="mb-2 mx-auto d-block" src="{% static "images/logo.png" %}" alt="" width="100" height="100">
        <h3 class="h3 mb-3 fw-normal">Reset your password</h3>
        <div class="small mb-3 text-muted">Enter your email address and we will send you a link to get back into your account.</div>
        {{form | crispy}}

        
        <button class="btn btn-primary w-100 py-2 mt-2" type="submit">Send link</button>
    </form>
</main>
{% endblock content %}

templates/sidebar.html
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            
             <!--Sidebar link header-->
            <div class="sb-sidenav-menu-heading">Core</div>
            <!--Sidebar link header-->

            <!--Normal sidebar-->
            <!--<a class="nav-link" href="{% url "home" %}"><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>Dashboard</a> -->
            <a class="nav-link" href="{% url "dashboard" %}"><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>Dashboard</a>
            <a class="nav-link" href="{% url "all-topics" %}"><div class="sb-nav-link-icon"><i class="fas fa-lightbulb"></i></div>Add topics</a>
            <a class="nav-link" href="{% url "profile" %}"><div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>My profile</a>
            
            <!--end of Normal sidebar-->

            <div class="sb-sidenav-menu-heading">EXAM</div>
             <!--section breaker-->
            
             <!--Normal sidebar-->
            {% comment %} <a class="nav-link" href="{% url "view-all-questions" %}"><div class="sb-nav-link-icon"><i class="fas fa-folder-open"></i></div>Questions</a> {% endcomment %}
            <a class="nav-link" href="{% url "all-questions" %}"><div class="sb-nav-link-icon"><i class="fas fa-database"></i></div>All questions</a>
            <a class="nav-link" href="{% url "scheduled-exam" %}"><div class="sb-nav-link-icon"><i class="fas fa-hourglass-half"></i></div>Scheduled Exam</a>
            <a class="nav-link" href="{% url "closed-exam" %}"><div class="sb-nav-link-icon"><i class="fas fa-check-double"></i></div>Closed Exams</a>

            
            <div class="sb-sidenav-menu-heading">STUDENT</div>
            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-clipboard-list"></i></div>
                Students Scoresheet
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    {% for subject in request.user.subject_set.all %}
                        <a class="nav-link" href="{% url "assessment" subject.id %}">{{subject.name}}</a>
                    {% endfor %}
                    
                    
                </nav>
            </div>
            <a class="nav-link" href="{% url "change-students-password" %}"><div class="sb-nav-link-icon"><i class="fas fa-lock-open"></i></div> Reset password</a>
            
           
           
            
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">{{request.user.get_full_name}}</div>
        
    </div>
</nav>

templates/verify_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Verification</title>
</head>
<body>
    <h1>Email Verification</h1>
    <p>Thank you {{user}}, for signing up! Please click the link below to verify your email address:</p>
    <p><a href="http://127.0.0.1:8000/lobby/?token=y12345">Verify Email</a></p>
    <p>If you did not sign up, please ignore this email.</p>
</body>
</html>